spring:
  application:
    name: wdusb-midterm
  profiles:
    active: dev

  main:
    web-application-type: servlet
    banner-mode: off
    log-startup-info: false

  jpa:
    open-in-view: false

app:
  api:
    base-url: http://localhost:8080

springdoc:
  packages-to-scan: tech.provokedynamic.wdusbmidterm.controller
  paths-to-match: /api/**

gg:
  jte:
    template-location: src/main/jte
    template-suffix: .kte

---

spring:
  config:
    activate:
      on-profile: dev

  datasource:
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres

  jpa:
    properties:
      hibernate.format_sql: true

gg:
  jte:
    development-mode: true

---

spring:
  config:
    activate:
      on-profile: prod

  datasource:
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRES_URL}

gg:
  jte:
    usePrecompiledTemplates: true