spring:
  application:
    name: wdusb-midterm
  profiles:
    active: dev

  main:
    web-application-type: servlet
    banner-mode: off
    log-startup-info: false

  jpa:
    open-in-view: false

gg:
  jte:
    development-mode: true
    template-location: src/main/jte
    template-suffix: .jte

---

spring:
  config:
    activate:
      on-profile: dev

  datasource:
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres

logging:
  level:
    root: info

---

spring:
  config:
    activate:
      on-profile: prod

  datasource:
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRES_URL}

gg:
  jte:
    usePrecompiledTemplates: true

logging:
  level:
    root: warn