-- H2-compatible users table (dev profile only)
-- H2 does not support ON CONFLICT — use MERGE INTO instead

CREATE TABLE IF NOT EXISTS users
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role          VARCHAR(20)  NOT NULL DEFAULT 'USER'
                               CHECK (role IN ('USER', 'ADMIN')),
    enabled       BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- admin / password: admin123  (bcrypt)
MERGE INTO users (username, password_hash, role)
KEY (username)
VALUES ('admin', '$2a$10$bOEnYYFOQGf57ZGv4JOtRuP7LO3LbupFxEO1WpIKo7zP0fBkEoBeq', 'ADMIN');

-- user / password: user123  (bcrypt)
MERGE INTO users (username, password_hash, role)
KEY (username)
VALUES ('user', '$2a$10$ctJTWu83HUDI04ZkGBQXUefXnh/KzA7Z3kfRdj8.bv7oy3MqFP64G', 'USER');
