INSERT INTO authors (firstname, lastname, email, dob, bio)
VALUES ('F. Scott', 'Fitzgerald', 'fscott@example.com', '1896-09-24',
        'American novelist, essayist, and short story writer.'),
       ('Jane', 'Austen', 'jausten@example.com', '1775-12-16',
        'English novelist known primarily for her six major novels.'),
       ('George', 'Orwell', 'gorwell@example.com', '1903-06-25', 'English novelist, essayist, journalist and critic.'),
       ('J.R.R.', 'Tolkien', 'jrrt@example.com', '1892-01-03', 'English writer, poet, philologist, and academic.'),
       ('Agatha', 'Christie', 'achristie@example.com', '1890-09-15',
        'English writer known for her 66 detective novels.'),
       ('Stephen', 'King', 'sking@example.com', '1947-09-21',
        'American author of horror, supernatural fiction, suspense, and fantasy.'),
       ('Isaac', 'Asimov', 'iasimov@example.com', '1920-01-02',
        'American writer and professor of biochemistry at Boston University.'),
       ('Toni', 'Morrison', 'tmorrison@example.com', '1931-02-18',
        'American novelist and essayist. Nobel Prize winner.'),
       ('Gabriel', 'Garcia Marquez', 'ggmarquez@example.com', '1927-03-06',
        'Colombian novelist, short-story writer, screenwriter, and journalist.'),
       ('Haruki', 'Murakami', 'hmurakami@example.com', '1949-01-12',
        'Japanese writer. His books and stories have been bestsellers in Japan as well as internationally.');